### ISSUE TITLE
Search Index Сonstruction Leads to an OutOfMemoryError

### ISSUE THREAD

**Issue by IvanMamontov** [iinegve/muCommander#26]
In some cases, for example, when we are trying to search at the root an application throws OutOfMemoryError. The main reason for this is bypassing archives. So we need to investigate it.

**Comment by iinegve** [comment]
I didn't get what is the issue. It is probably the one that you mentioned opened stream for archives... Is that so?

**Comment by IvanMamontov** [comment]
I didn't have much time to investigate it. I think we need to check it.
